name: SMSpp_builder
channels:
  - bioconda
  - gurobi
  - ibmdecisionoptimization
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - snakemake-minimal
  # - asyncore  #

  - numpy<2
  - pandas
  - matplotlib

  # for the exercises on pypsa
  - pypsa
  - glpk
  - gurobi
  - cplex
  - highspy

  # for jupyter
  - jupyter
  - ipython
  - ipykernel

  # SMSpp interaction
  - netCDF4
  - ncompare

  # plotting
  - graphviz
 
  - pip:
    - git+https://github.com/davide-f/google-drive-downloader@disable_print  # google drive with fix for virus scan